import { atom } from "recoil";

export const clientsState = atom({
  key: "clientsState",
  default: [
    {
      id: 1,
      name: "가길동",
      nickname: "알렉스",
      danger: "safe",
      contact: "010-1234-5678",
      address: "서울특별시 강남구 압구정로 151-2 108동 504호",
      birth: "1990.01.01 (만 34세)",
      email: "alex@example.com",
      gender: "남자",
      job: "회사원",
      guardians: "김매순 (모) 010-1234-5678",
      memo: "특이사항 없음.",
      session: "1회기",
      todos: ["심리검사 요청", "녹취록 분석", "상담일지 작성", "사례개념화 최초 작성"],
    },
    {
      id: 2,
      name: "나길동",
      nickname: "니니동",
      danger: "caution",
      contact: "010-1234-5678",
      address: "서울특별시 중구 세종대로 110",
      birth: "1995.05.05 (만 29세)",
      email: "nini@example.com",
      gender: "여자",
      job: "학생",
      guardians: "김복남 (부) 010-1234-5678",
      memo: "상담 초기 단계.",
      session: "2회기",
      todos: ["녹취록 분석", "상담일지 작성", "사례개념화 최초 작성"],
    },
    {
      id: 3,
      name: "김마음",
      nickname: "카이막",
      danger: "danger",
      contact: "010-1234-1234",
      address: "서울특별시 강남구 압구정로 151-2 108동 504호",
      birth: "2005.04.22 (만 18세)",
      email: "kimmau@gmail.com",
      gender: "남자",
      job: "대학생",
      guardians: "김매순 (모) 010-1234-1234, 김복남 (부) 010-1234-1234 한마음 (사회복지사) 010-1234-1234",
      memo: "본 환자는 최근 몇 개월 간 지속적인 우울감, 무기력, 수면장애 및 식욕 저하를 호소하며 내원하였습니다.",
      session: "4회기",
      todos: ["상담일지 작성", "사례개념화 최초 작성"],
    },
    {
      id: 4,
      name: "라길동",
      nickname: "라떼길",
      danger: "critical",
      contact: "010-1234-5678",
      address: "경기도 수원시 팔달구",
      birth: "1985.12.12 (만 39세)",
      email: "latte@example.com",
      gender: "남자",
      job: "프리랜서",
      guardians: "김매순 (모) 010-1234-5678",
      memo: "장기 상담 진행 중.",
      session: "6회기",
      todos: ["사례개념화 최초 작성"],
    },
    {
      id: 5,
      name: "마길동",
      nickname: "고양이",
      danger: "safe",
      contact: "010-1234-5678",
      address: "부산광역시 해운대구",
      birth: "2000.07.07 (만 24세)",
      email: "cat@example.com",
      gender: "여자",
      job: "디자이너",
      guardians: "김복남 (부) 010-1234-5678",
      memo: "최근 상담 불참.",
      session: "99회기",
      todos: ["상담일지 작성"],
    },
    {
      id: 6,
      name: "사길동",
      danger: "caution",
      contact: "010-1234-5678",
      address: "대전광역시 유성구",
      birth: "1992.03.03 (만 32세)",
      email: "sa@example.com",
      gender: "남자",
      job: "연구원",
      guardians: "김매순 (모) 010-1234-5678",
      memo: "신규 등록.",
      session: "신규",
      todos: [],
      isNew: true,
    },
    {
      id: 7,
      name: "바길동",
      nickname: "강아지",
      danger: "safe",
      contact: "010-1234-5678",
      address: "인천광역시 남동구",
      birth: "1998.09.09 (만 26세)",
      email: "dog@example.com",
      gender: "여자",
      job: "마케터",
      guardians: "김복남 (부) 010-1234-5678",
      memo: "상담 꾸준히 참석.",
      session: "99회기",
      todos: ["상담일지 작성"],
    },
  ],
});
